#!/usr/bin/env bash

# dmenu cannot display more than 30 lines, to avoid screen clutter. Only relevant if you have more than 30 windows open.
height=$(wmctrl -l | wc -l)
if [[ $height -gt 30 ]]
	then heightfit=30
	else heightfit=$height
fi

num=$(wmctrl -xl \
     | sed 's/  / /' \
     | cut -d " " -f 3- \
     | nl -w 3 -n rn \
     | sed -r 's/^([ 0-9]+)[ \t]*[^ \t]+\.([^ \t]+)[ \t]+[^ \t]+[ \t]+(.*)$/\1 - \2: \3/' \
     | dmenu -i -p "windows" -l $heightfit \
     | cut -d '-' -f -1)

[[ -z "$num" ]] && exit
wmctrl -l | sed -n "$num p" | cut -c -10 | xargs wmctrl -i -a
